name: Build Snapclient for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Snapcast source
      uses: actions/checkout@v3
      with:
        repository: badaix/snapcast
        submodules: true

    - name: Install dependencies
      run: |
        choco install cmake -y
        choco install git -y

    - name: Setup vcpkg and install dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install boost-program-options libflac libogg libvorbis opus soxr
        echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" >> $env:GITHUB_ENV
        echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $env:GITHUB_ENV


    - name: Configure and build snapclient
      run: |
        mkdir build
        cd build
        cmake .. -A x64 `
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake `
          -DBUILD_SERVER=OFF `
          -DBUILD_CLIENT=ON
        cmake --build . --config Release

    - name: Upload snapclient.exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: snapclient
        path: build/client/Release/snapclient.exe
