name: Build Snapclient for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Snapcast source
      uses: actions/checkout@v3
      with:
        repository: badaix/snapcast
        submodules: true

    - name: Install dependencies
      run: |
        choco install cmake -y
        choco install git -y

    - name: Restore vcpkg cache
      uses: actions/cache@v4
      id: cache-vcpkg
      with:
        path: |
          vcpkg/installed
          vcpkg/buildtrees
          vcpkg/packages
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Setup vcpkg and install dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install boost boost-system boost-thread boost-asio flac libogg libvorbis opus soxr
      env:
        VCPKG_DEFAULT_TRIPLET: x64-windows

    - name: Set environment variables
      run: |
        echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" >> $env:GITHUB_ENV
        echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $env:GITHUB_ENV

    - name: Configure and build snapclient
      run: |
        mkdir build
        cd build
        cmake .. -A x64 `
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake `
          -DBUILD_SERVER=OFF `
          -DBUILD_CLIENT=ON
        cmake --build . --config Release

    - name: Debug — list build output
      run: |
        echo "Searching for snapclient.exe..."
        dir /s /b snapclient.exe

    - name: Upload snapclient.exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: snapclient
        path: bin/Release/snapclient.exe
